### ISSUE TITLE
loader.load in web worker?

### ISSUE THREAD

**Issue by tarun29061990** [mhelvens/apinatomy#21]
JSON Loader load function uses document object to create Image element for loading textures. You can see the code of THREE.ImageLoader.load() function. How you made it work in a web worker because web worker doesn't have context of DOM, window, etc. ?

**Comment by mhelvens** [comment]
We've abandoned the web-worker stuff for the time being, because lots of other stuff didn't yet work. I'm afraid this is not the right place to ask such questions right now. Perhaps THREE didn't do that at the time we experimented with web workers?
